# frozen_string_literal: true

[
  {
    index: 0,
    stepper_type: 'startup_deal',
    title: 'instrument',
    title_ar: 'أداة',
    sections_attributes: [
      {
        index: 0,
        title: 'Instrument Type',
        title_ar: 'نوع الصك',
        description: nil,
        description_ar: nil,
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Select an instrument to raise funds',
            statement_ar: 'حدد أداة لجمع الأموال',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'multiple_choice',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'funding_round_attributes.instrument_type_id',
            input_type: 'currency',
            options_attributes: [
              {
                statement: 'Equity Financing',
                statement_ar: 'تمويل أسهم رأس المال',
                index: 1,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: 'Sell shares in exchange for capital',
                label_ar: 'بيع الأسهم مقابل رأس المال'
              },
              {
                statement: 'SAFE',
                statement_ar: 'آمن',
                index: 0,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: 'Commit to future equity for investors',
                label_ar: 'الالتزام بالأسهم المستقبلية للمستثمرين'
              }
            ]
          },
          {
            index: 1,
            statement: 'SAFE Type',
            statement_ar: 'نوع آمن',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'multiple_choice',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'funding_round_attributes.safe_type_id',
            input_type: 'currency',
            options_attributes: [
              {
                statement: 'Valuation Cap, No Discount',
                statement_ar: 'سقف التقييم، لا يوجد خصم',
                index: 1,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: 'Provide a maximum valuation',
                label_ar: 'تقديم الحد الأقصى للتقييم'
              },
              {
                statement: 'Discount, No Valuation Cap',
                statement_ar: 'الخصم، لا سقف للتقييم',
                index: 0,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: 'Offer a discounted price per share',
                label_ar: 'تقديم سعر مخفض للسهم الواحد'
              },
              {
                statement: 'No Valuation Cap, No Discount',
                statement_ar: 'شائع',
                index: 2,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: 'Offer investor same terms as subsequent investors, sans a cap or discount',
                label_ar: 'إعطاء أسهم الملكية وحقوق التصويت'
              }
            ]
          },
          {
            index: 1,
            statement: 'Equity Type',
            statement_ar: 'نوع الأسهم',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'multiple_choice',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'funding_round_attributes.equity_type_id',
            input_type: 'currency',
            options_attributes: [
              {
                statement: 'Preferred',
                statement_ar: 'يفضل',
                index: 0,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: 'Pay fixed dividends regularly',
                label_ar: 'دفع أرباح ثابتة بانتظام'
              },
              {
                statement: 'Common',
                statement_ar: 'شائع',
                index: 1,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: 'Give shares of ownership and voting rights',
                label_ar: 'إعطاء أسهم الملكية وحقوق التصويت'
              }
            ]
          }
        ]
      }
    ]
  },

  {
    index: 1,
    stepper_type: 'startup_deal',
    title: 'stage',
    title_ar: 'منصة',
    sections_attributes: [
      {
        index: 0,
        title: 'Stage',
        title_ar: 'منصة',
        description: nil,
        description_ar: nil,
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'What is your funding stage?',
            statement_ar: 'ما هي مرحلة التمويل الخاصة بك؟',
            label: 'This will help you meet your next milestone',
            label_ar: 'سيساعدك هذا على تحقيق إنجازك التالي',
            description: '',
            description_ar: '',
            is_required: true,
            field_type: 'multiple_choice',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'funding_round_attributes.round_id',
            input_type: 'currency',
            options_attributes: [
              {
                statement: 'Series A',
                statement_ar: 'السلسلة أ',
                index: 2,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: nil,
                label_ar: nil
              },
              {
                statement: 'Mezzanine & bridge',
                statement_ar: 'الميزانين والجسر',
                index: 6,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: nil,
                label_ar: nil
              },
              {
                statement: 'Pre-seed',
                statement_ar: 'ما قبل البذور',
                index: 0,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: nil,
                label_ar: nil
              },
              {
                statement: 'Seed / Angel',
                statement_ar: 'بذرة / ملاك',
                index: 1,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: nil,
                label_ar: nil
              },
              {
                statement: 'Series B',
                statement_ar: 'السلسلة ب',
                index: 3,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: nil,
                label_ar: nil
              },
              {
                statement: 'Series C',
                statement_ar: 'السلسلة ج',
                index: 4,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: nil,
                label_ar: nil
              },
              {
                statement: 'Series D',
                statement_ar: 'السلسلة د',
                index: 5,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: nil,
                label_ar: nil
              }
            ]
          }
        ]
      }
    ]
  },

  {
    index: 2,
    stepper_type: 'startup_deal',
    title: 'Title',
    title_ar: 'عنوان',
    sections_attributes: [
      {
        index: 0,
        title: 'Describe your deal',
        title_ar: nil,
        description: nil,
        description_ar: nil,
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Title',
            statement_ar: 'عنوان',
            label: 'Add Title.',
            label_ar: 'أضف عنوانا.',
            description: '',
            description_ar: '',
            is_required: true,
            field_type: 'text_field',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'title',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 1,
            statement: 'Startup description',
            statement_ar: 'وصف بدء التشغيل',
            label: 'Brief Description of the property',
            label_ar: 'وصف موجز للعقار',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_box',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'description',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      }
    ]
  },

  {
    index: 3,
    stepper_type: 'startup_deal',
    title: 'round size',
    title_ar: 'حجم دائري',
    sections_attributes: [
      {
        index: 0,
        title: 'Round Size',
        title_ar: 'حجم دائري',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'How much do you need to raise?',
            statement_ar: 'كم تحتاج إلى رفع؟',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [500_000.0, 1_000_000.0, 2_000_000.0, 3_000_000.0],
            field_mapping: 'target',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      }
    ]
  },

  {
    index: 4,
    stepper_type: 'startup_deal',
    title: 'valuation',
    title_ar: 'تقييم',
    sections_attributes: [
      {
        index: 0,
        title: 'Valuation',
        title_ar: 'تقييم',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Estimated Value',
            statement_ar: 'القيمة المقدرة',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'funding_round_attributes.valuation',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 1,
            statement: 'Type',
            statement_ar: 'يكتب',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'dropdown',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'funding_round_attributes.valuation_phase_id',
            input_type: 'currency',
            options_attributes: [
              {
                statement: 'Post-Money Valuation',
                statement_ar: 'تقييم ما بعد المال',
                index: 1,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              },
              {
                statement: 'Pre-Money Valuation',
                statement_ar: 'التقييم المسبق للنقود',
                index: 0,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              }
            ]
          }
        ]
      }
    ]
  },

  {
    index: 5,
    stepper_type: 'startup_deal',
    title: 'attachments',
    title_ar: 'المرفقات',
    sections_attributes: [
      {
        index: 0,
        title: 'Add Attachments',
        title_ar: 'أضف ملحقات',
        description: 'Upload the necessary documents',
        description_ar: 'قم بتحميل المستندات اللازمة',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 2,
            statement: 'Business Plan',
            statement_ar: 'خطة عمل',
            label: 'A comprehensive document outlining the business strategy, market analysis, and financial projections.',
            label_ar: 'وثيقة شاملة تحدد استراتيجية العمل، وتحليل السوق، والتوقعات المالية.',
            description: 'To provide an in-depth understanding of the business  model and its growth prospects.',
            description_ar: 'لتوفير فهم متعمق لنموذج الأعمال وآفاق نموه.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 1,
            statement: 'Financial Statements',
            statement_ar: 'القوائم المالية',
            label: 'Historical financial records  for the past three years.',
            label_ar: 'السجلات المالية التاريخية للسنوات الثلاث الماضية.',
            description: "To offer insight into the startup's  financial health.",
            description_ar: "لتقديم نظرة ثاقبة على الصحة المالية للشركة الناشئة.\n",
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 11,
            statement: 'SWOT Analysis',
            statement_ar: 'تحليل SWOT',
            label: 'Analysis of Strengths, Weaknesses, Opportunities, and Threats.',
            label_ar: 'تحليل نقاط القوة والضعف والفرص والتهديدات.',
            description: 'To offer a balanced perspective  of risks and potential.',
            description_ar: 'تقديم منظور متوازن للمخاطر والإمكانات.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 3,
            statement: 'Market Research Report',
            statement_ar: 'تقرير أبحاث السوق',
            label: 'Detailed analysis of target  market',
            label_ar: 'تحليل مفصل للسوق المستهدف',
            description: 'To validate the market opportunity.',
            description_ar: 'للتحقق من صحة فرصة السوق.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 4,
            statement: "Founders' CVs",
            statement_ar: 'السيرة الذاتية للمؤسسين',
            label: 'Resumes of each founder.',
            label_ar: 'السيرة الذاتية لكل مؤسس.',
            description: "To showcase the founders' skills  and experience.",
            description_ar: 'إبراز مهارات وخبرات المؤسسين.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 5,
            statement: 'Corporate Structure Diagram',
            statement_ar: 'مخطط هيكل الشركة',
            label: 'Visual representation of  organizational structure',
            label_ar: 'التمثيل المرئي للهيكل التنظيمي',
            description: 'To clarify organizational setup  and key personnel.',
            description_ar: 'لتوضيح الإعداد التنظيمي والموظفين الرئيسيين.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 6,
            statement: 'Legal Entity Documents',
            statement_ar: 'وثائق الكيان القانوني',
            label: 'Documents like Certificate  of Incorporation, etc.',
            label_ar: 'وثائق مثل شهادة التأسيس، الخ.',
            description: 'To confirm legal status and compliance.',
            description_ar: 'لتأكيد الوضع القانوني والامتثال.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 7,
            statement: 'IP Rights Documentation',
            statement_ar: 'توثيق حقوق الملكية الفكرية',
            label: 'Documents supporting any  intellectual property rights.',
            label_ar: 'المستندات الداعمة لأي حقوق ملكية فكرية.',
            description: 'To verify proprietary assets.',
            description_ar: 'للتحقق من الأصول الملكية.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 8,
            statement: 'Initial Valuation Report ',
            statement_ar: 'تقرير التقييم الأولي',
            label: "Preliminary estimate of the  startup's value.",
            label_ar: 'تقدير أولي لقيمة الشركة الناشئة.',
            description: 'To facilitate negotiation and  decision-making.',
            description_ar: 'لتسهيل التفاوض واتخاذ القرار.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 9,
            statement: 'Cap Table',
            statement_ar: 'جدول كاب',
            label: 'A table showing the ownership structure of the  company, including shares held by each stakeholder.',
            label_ar: 'جدول يوضح هيكل ملكية الشركة بما في ذلك الأسهم المملوكة لكل صاحب مصلحة.',
            description: 'To understand the ownership  distribution and stakeholder  equity.',
            description_ar: 'لفهم توزيع الملكية وحقوق المساهمين.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 10,
            statement: 'Investment Memo',
            statement_ar: 'مذكرة الاستثمار',
            label: 'A detailed memorandum  outlining the investment  opportunity, terms, and  conditions.',
            label_ar: 'مذكرة تفصيلية توضح فرصة الاستثمار وشروطه وأحكامه.',
            description: 'To provide prospective investors  with necessary information for  decision-making.',
            description_ar: 'لتزويد المستثمرين المحتملين بالمعلومات اللازمة لاتخاذ القرار.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 0,
            statement: 'Investor Presentation or Pitch Deck',
            statement_ar: 'العرض التقديمي للمستثمر أو العرض الترويجي',
            label: 'A slide presentation summarizing the business  and investment opportunity.',
            label_ar: 'عرض شرائح يلخص الفرص التجارية والاستثمارية.',
            description: 'To present to potential investors  in meetings or pitches.',
            description_ar: 'لتقديمها للمستثمرين المحتملين في الاجتماعات أو الملاعب.',
            is_required: true,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 12,
            statement: 'Lead Syndicate Profile &  Credentials',
            statement_ar: 'ملف تعريف النقابة وبيانات الاعتماد',
            label: 'Detailed information about  the lead syndicate, their  track record, and qualifications.',
            label_ar: 'معلومات تفصيلية عن النقابة الرائدة وسجلها الحافل ومؤهلاتها.',
            description: 'To establish credibility and  attract potential co-investors.',
            description_ar: 'ترسيخ المصداقية وجذب المستثمرين المشاركين المحتملين.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 13,
            statement: 'Term Sheet',
            statement_ar: 'ورقة المصطلح',
            label: 'A preliminary agreement  outlining the terms of the  investment.',
            label_ar: 'اتفاقية مبدئية تحدد شروط الاستثمار.',
            description: 'To serve as a basis for final  negotiations and legal agreements.',
            description_ar: 'لتكون بمثابة أساس للمفاوضات النهائية والاتفاقات القانونية.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 14,
            statement: 'Projections',
            statement_ar: 'التوقعات',
            label: 'Forecasted revenue, expenses, and other financial metrics for future years.',
            label_ar: 'الإيرادات والنفقات المتوقعة والمقاييس المالية الأخرى للسنوات المقبلة.',
            description: 'To provide a financial outlook and support valuation discussions.',
            description_ar: 'لتقديم نظرة مالية ودعم مناقشات التقييم.',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 15,
            statement: 'Due Diligence Report',
            statement_ar: 'تقرير العناية الواجبة',
            label: 'A report summarizing the findings of due diligence investigations, including legal, financial, and operational aspects.',
            label_ar: 'تقرير يلخص نتائج تحقيقات العناية الواجبة، بما في ذلك الجوانب القانونية والمالية والتشغيلية.',
            description: 'To inform all parties of potential risks and validate the information provided',
            description_ar: 'لإبلاغ جميع الأطراف بالمخاطر المحتملة والتحقق من صحة المعلومات المقدمة',
            is_required: false,
            field_type: 'file',
            permitted_types: %w[pdf png],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          }
        ]
      }
    ]
  },

  {
    index: 6,
    stepper_type: 'startup_deal',
    title: 'Deal Timeline',
    title_ar: 'الجدول الزمني للصفقة',
    sections_attributes: [
      {
        index: 0,
        title: 'Select date',
        title_ar: 'حدد تاريخ',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 1,
            statement: 'end date',
            statement_ar: 'تاريخ الانتهاء',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'date',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'end_at',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 0,
            statement: 'start date',
            statement_ar: 'تاريخ البدء',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: true,
            field_type: 'date',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'start_at',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      }
    ]
  },
  {
    index: 7,
    stepper_type: 'startup_deal',
    title: 'terms',
    title_ar: 'شروط',
    sections_attributes: [
      {
        index: 0,
        title: 'Terms',
        title_ar: 'شروط',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: 'safe',
        fields_attributes: [
          {
            index: 0,
            statement: 'Valuation Cap',
            statement_ar: 'سقف التقييم',
            label: 'Description related valuation cap',
            label_ar: 'وصف سقف التقييم ذات الصلة',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.enabled',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 4,
            statement: 'MFN Only',
            statement_ar: 'الدولة الأولى بالرعاية فقط',
            label: 'Description related MFN',
            label_ar: 'وصف الدولة الأكثر رعاية (MFN) ذات الصلة',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.enabled',
            input_type: 'boolean',
            options_attributes: []
          },
          {
            index: 10,
            statement: 'Additional Terms',
            statement_ar: 'شروط إضافية',
            label: 'Description related additional terms',
            label_ar: 'وصف المصطلحات الإضافية ذات الصلة',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.enabled',
            input_type: '_text',
            options_attributes: []
          },
          {
            index: 1,
            statement: 'Valuation Cap',
            statement_ar: 'سقف التقييم',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.custom_input',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 2,
            statement: 'Discount',
            statement_ar: 'تخفيض',
            label: 'Description related discount',
            label_ar: 'وصف الخصم ذات الصلة',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.enabled',
            input_type: 'percent',
            options_attributes: []
          },
          {
            index: 3,
            statement: 'Discount',
            statement_ar: 'تخفيض',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.custom_input',
            input_type: 'percent',
            options_attributes: []
          },
          {
            index: 6,
            statement: 'Minimum Check Size',
            statement_ar: 'الحد الأدنى لحجم الشيك',
            label: 'Description related investment',
            label_ar: 'وصف الاستثمار ذات الصلة',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.enabled',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 7,
            statement: 'Minimum Check Size',
            statement_ar: 'الحد الأدنى لحجم الشيك',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.custom_input',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 8,
            statement: 'Pro Rata',
            statement_ar: 'تناسبي',
            label: 'Description related Pro Rata',
            label_ar: 'الوصف ذو الصلة التناسبي',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.enabled',
            input_type: 'boolean',
            options_attributes: []
          },
          {
            index: 11,
            statement: 'Additional Terms',
            statement_ar: 'شروط إضافية',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_box',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.custom_input',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      },
      {
        index: 0,
        title: 'Terms',
        title_ar: 'شروط',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: 'equity',
        fields_attributes: [
          {
            index: 10,
            statement: 'Additional Terms',
            statement_ar: 'شروط إضافية',
            label: 'Description related additional terms',
            label_ar: 'وصف المصطلحات الإضافية ذات الصلة',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.enabled',
            input_type: '_text',
            options_attributes: []
          },
          {
            index: 6,
            statement: 'Minimum Check Size',
            statement_ar: 'الحد الأدنى لحجم الشيك',
            label: 'Description related investment',
            label_ar: 'وصف الاستثمار ذات الصلة',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.enabled',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 7,
            statement: 'Minimum Check Size',
            statement_ar: 'الحد الأدنى لحجم الشيك',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.custom_input',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 8,
            statement: 'Pro Rata',
            statement_ar: 'تناسبي',
            label: 'Description related Pro Rata',
            label_ar: 'الوصف ذو الصلة التناسبي',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.enabled',
            input_type: 'boolean',
            options_attributes: []
          },
          {
            index: 11,
            statement: 'Additional Terms',
            statement_ar: 'شروط إضافية',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_box',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'terms_attributes.custom_input',
            input_type: '_text',
            options_attributes: []
          }
        ]
      }
    ]
  },
  {
    index: 8,
    stepper_type: 'startup_deal',
    title: 'review',
    title_ar: 'مراجعة',
    sections_attributes: [
      {
        index: 0,
        title: 'Review',
        title_ar: 'مراجعة',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: []
      }
    ]
  },
  {
    index: 0,
    stepper_type: 'property_deal',
    title: 'Property Details',
    title_ar: 'تفاصيل اوضح',
    sections_attributes: [
      {
        index: 1,
        title: 'Location',
        title_ar: 'موقع',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Country',
            statement_ar: 'دولة',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'dropdown',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.country_id',
            input_type: 'currency',
            options_attributes: [
              {
                statement: 'Bahrain',
                statement_ar: 'البحرين',
                index: 0,
                unit: 'Million',
                currency: 'USD',
                is_range: nil,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              },
              {
                statement: 'Kuwait',
                statement_ar: 'الكويت',
                index: 1,
                unit: 'Million',
                currency: 'USD',
                is_range: nil,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              },
              {
                statement: 'Qatar',
                statement_ar: 'دولة قطر',
                index: 2,
                unit: 'Million',
                currency: 'USD',
                is_range: nil,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              },
              {
                statement: 'Oman',
                statement_ar: 'سلطنة عمان',
                index: 3,
                unit: 'Million',
                currency: 'USD',
                is_range: nil,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              },
              {
                statement: 'Saudi Arabia',
                statement_ar: 'المملكة العربية السعودية',
                index: 4,
                unit: 'Million',
                currency: 'USD',
                is_range: nil,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              },
              {
                statement: 'United Arab Emirate',
                statement_ar: 'الإمارات العربية المتحدة',
                index: 5,
                unit: 'Million',
                currency: 'USD',
                is_range: nil,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              }
            ]
          },
          {
            index: 1,
            statement: 'State',
            statement_ar: 'ولاية',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_field',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.state',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 2,
            statement: 'City',
            statement_ar: 'مدينة',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_field',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.city',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 3,
            statement: 'Area',
            statement_ar: 'منطقة',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_field',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.area',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 4,
            statement: 'Building Name',
            statement_ar: 'اسم المبنى',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_field',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.building_name',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 5,
            statement: 'Street Address',
            statement_ar: 'عنوان الشارع',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_field',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.street_address',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      },
      {
        index: 2,
        title: 'Size',
        title_ar: 'مقاس',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Size',
            statement_ar: 'مقاس',
            label: '500 sqft',
            label_ar: '500 قدم مربع',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.size',
            input_type: 'sqft',
            options_attributes: []
          }
        ]
      },
      {
        index: 3,
        title: 'Features',
        title_ar: 'سمات',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 1,
            statement: 'Bedrooms',
            statement_ar: 'غرف نوم',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.no_bedrooms',
            input_type: 'numeric',
            options_attributes: []
          },
          {
            index: 3,
            statement: 'Kitchen',
            statement_ar: 'مطبخ',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.no_kitchen',
            input_type: 'numeric',
            options_attributes: []
          },
          {
            index: 5,
            statement: 'Washrooms',
            statement_ar: 'دورات المياه',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.no_washrooms',
            input_type: 'numeric',
            options_attributes: []
          },
          {
            index: 6,
            statement: 'Parking',
            statement_ar: 'موقف سيارات',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.has_parking',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 7,
            statement: 'Parking',
            statement_ar: 'موقف سيارات',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.parking_capacity',
            input_type: 'numeric',
            options_attributes: []
          },
          {
            index: 11,
            statement: 'duration',
            statement_ar: 'مدة',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'dropdown',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.rental_period_id',
            input_type: 'currency',
            options_attributes: [
              {
                statement: 'Monthly',
                statement_ar: 'شهريا',
                index: 0,
                unit: 'Million',
                currency: 'USD',
                is_range: nil,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              },
              {
                statement: 'Yearly',
                statement_ar: 'سنوي',
                index: 1,
                unit: 'Million',
                currency: 'USD',
                is_range: nil,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              }
            ]
          },
          {
            index: 12,
            statement: 'rent',
            statement_ar: 'إيجار',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.rental_amount',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 0,
            statement: 'Bedrooms',
            statement_ar: 'غرف نوم',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.has_bedrooms',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 2,
            statement: 'Kitchen',
            statement_ar: 'مطبخ',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.has_kitchen',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 4,
            statement: 'Washrooms',
            statement_ar: 'دورات المياه',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.has_washroom',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 8,
            statement: 'Swimming Pool',
            statement_ar: 'حمام السباحة',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.has_swimming_pool',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 9,
            statement: 'Swimming Pool',
            statement_ar: 'حمام السباحة',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'dropdown',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.swimming_pool_id',
            input_type: 'currency',
            options_attributes: [
              {
                statement: 'Shared',
                statement_ar: 'مشترك',
                index: 0,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              },
              {
                statement: 'Private',
                statement_ar: 'خاص',
                index: 1,
                unit: 'Million',
                currency: 'USD',
                is_range: false,
                lower_limit: nil,
                uper_limit: nil,
                label: '',
                label_ar: ''
              }
            ]
          },
          {
            index: 10,
            statement: 'Property on a rent?',
            statement_ar: 'عقار للإيجار؟',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'switch',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'property_detail_attributes.is_rental',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      },
      {
        index: 13,
        title: 'Property Description',
        title_ar: 'وصف العقار',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Property Description',
            statement_ar: 'وصف العقار',
            label: 'Brief Description of the property',
            label_ar: 'وصف موجز للعقار',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_box',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'description',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      },
      {
        index: 0,
        title: 'Property Details',
        title_ar: 'تفاصيل اوضح',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Title',
            statement_ar: 'عنوان',
            label: 'Add Title.',
            label_ar: 'أضف عنوانا.',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_field',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'title',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      }
    ]
  },
  {
    index: 1,
    stepper_type: 'property_deal',
    title: 'Unique Selling Points',
    title_ar: 'نقاط بيع فريدة من نوعها',
    sections_attributes: [
      {
        index: 0,
        title: 'Unique Selling Points',
        title_ar: 'نقاط بيع فريدة من نوعها',
        description: '',
        description_ar: '',
        is_multiple: true,
        add_more_label: '+ Add new point',
        add_more_label_ar: '+ إضافة نقطة جديدة',
        display_card: true,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Title',
            statement_ar: 'عنوان',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_field',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'features_attributes.title',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 1,
            statement: 'Description',
            statement_ar: 'وصف',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'text_box',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'features_attributes.description',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      }
    ]
  },
  {
    index: 2,
    stepper_type: 'property_deal',
    title: 'Attachments',
    title_ar: 'المرفقات',
    sections_attributes: [
      {
        index: 0,
        title: 'Add Attachments',
        title_ar: 'أضف ملحقات',
        description: 'Upload the necessary documents.',
        description_ar: 'قم بتحميل المستندات اللازمة.',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Property Title',
            statement_ar: 'عنوان العقار',
            label: 'A legal document establishing property ownership.',
            label_ar: 'وثيقة قانونية تثبت ملكية العقار.',
            description: 'To verify ownership and ensure no disputes.',
            description_ar: 'للتحقق من الملكية وضمان عدم وجود نزاعات.',
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 1,
            statement: 'Property Appraisal Report',
            statement_ar: 'تقرير تقييم الممتلكات',
            label: 'Professional Valuation of  the property.',
            label_ar: 'التقييم المهني للعقار.',
            description: "To assess the property's market  value.",
            description_ar: 'لتقييم القيمة السوقية للعقار.',
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 2,
            statement: 'Current Lease Agreements',
            statement_ar: 'اتفاقيات الإيجار الحالية',
            label: 'Copies of any active lease  agreements.',
            label_ar: 'نسخ من أي اتفاقيات إيجار نشطة.',
            description: 'To assess current revenue  streams.',
            description_ar: 'لتقييم تدفقات الإيرادات الحالية.',
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 4,
            statement: 'Maintenance and Upkeep',
            statement_ar: 'الصيانة والصيانة',
            label: 'Documented history of  maintenance.',
            label_ar: 'التاريخ الموثق للصيانة.',
            description: "To understand the property's condition and future costs.",
            description_ar: 'لفهم حالة العقار والتكاليف المستقبلية.',
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 7,
            statement: 'Term Sheet',
            statement_ar: 'ورقة المصطلح',
            label: 'Basic terms and conditions  for investment.',
            label_ar: 'الشروط والأحكام الأساسية للاستثمار.',
            description: 'To clarify terms and expectations.',
            description_ar: 'لتوضيح الشروط والتوقعات.',
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 6,
            statement: 'Independent Property Report',
            statement_ar: 'تقرير الملكية المستقلة',
            label: 'A third-party report detailing property condition.',
            label_ar: 'تقرير طرف ثالث يوضح حالة العقار.',
            description: "To provide an unbiased evaluation of the property's condition.",
            description_ar: "تقديم تقييم غير متحيز لحالة العقار.\n",
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 5,
            statement: 'Financial Projections',
            statement_ar: 'التوقعات المالية',
            label: 'Forward-looking financial estimates.',
            label_ar: 'التقديرات المالية التطلعية.',
            description: 'To assess economic viability.',
            description_ar: 'لتقييم الجدوى الاقتصادية.',
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 3,
            statement: 'Local Area Report',
            statement_ar: 'تقرير المنطقة المحلية',
            label: 'Analysis of the local area  and market trends.',
            label_ar: 'تحليل المنطقة المحلية واتجاهات السوق.',
            description: 'To provide contextual background.',
            description_ar: 'لتوفير الخلفية السياقية.',
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 8,
            statement: 'Independent Area Report',
            statement_ar: 'تقرير المنطقة المستقلة',
            label: "Comprehensive analysis of  property's location.",
            label_ar: 'تحليل شامل لموقع العقار.',
            description: 'To provide contextual information.',
            description_ar: 'لتوفير المعلومات السياقية.',
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 9,
            statement: 'Lead Syndicate Profile',
            statement_ar: 'ملف تعريف النقابة',
            label: 'Information about the lead  syndicate.',
            label_ar: 'معلومات عن النقابة الرائدة.',
            description: 'To establish credibility.',
            description_ar: 'لتأسيس المصداقية.',
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 10,
            statement: '5-Year Proforma',
            statement_ar: 'نموذج 5 سنوات',
            label: 'Financial statement projecting metrics for the  next 5 years.',
            label_ar: 'بيان مالي يعرض المقاييس للسنوات الخمس القادمة.',
            description: 'To provide a long-term view.',
            description_ar: 'لتوفير رؤية طويلة المدى.',
            is_required: false,
            field_type: 'file',
            permitted_types: ['pdf'],
            size_constraints: { 'unit' => 'mb', 'limit' => 10 },
            suggestions: [],
            field_mapping: nil,
            input_type: 'currency',
            options_attributes: []
          }
        ]
      },
      {
        index: 1,
        title: 'Add Links',
        title_ar: 'إضافة روابط',
        description: 'Upload the necessary documents.',
        description_ar: 'قم بتحميل المستندات اللازمة.',
        is_multiple: true,
        add_more_label: '+ Add new link',
        add_more_label_ar: '+ إضافة رابط جديد',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'External Link',
            statement_ar: 'رابط خارجي',
            label: 'www.example.com',
            label_ar: 'www.example.com',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'url',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'external_links_attributes.url',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      }
    ]
  },
  {
    index: 3,
    stepper_type: 'property_deal',
    title: 'Selling Price',
    title_ar: 'سعر البيع',
    sections_attributes: [
      {
        index: 0,
        title: 'Selling Price',
        title_ar: 'سعر البيع',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Price',
            statement_ar: 'سعر',
            label: '0.00',
            label_ar: '0.00',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [500_000.0, 1_000_000.0, 2_000_000.0, 3_000_000.0],
            field_mapping: 'target',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      }
    ]
  },
  {
    index: 4,
    stepper_type: 'property_deal',
    title: 'Expected Return',
    title_ar: 'العودة المتوقعة',
    sections_attributes: [
      {
        index: 0,
        title: 'Expected Return',
        title_ar: 'العودة المتوقعة',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Expected Dividend Yield',
            statement_ar: 'عائد الأرباح المتوقع',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [2.5, 5.5, 8.5, 10.0],
            field_mapping: 'property_detail_attributes.dividend_yield',
            input_type: 'percent',
            options_attributes: []
          },
          {
            index: 1,
            statement: 'Expected Annual Appreciation',
            statement_ar: 'التقدير السنوي المتوقع',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'number',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [2.5, 5.5, 8.5, 10.0],
            field_mapping: 'property_detail_attributes.yearly_appreciation',
            input_type: 'percent',
            options_attributes: []
          }
        ]
      }
    ]
  },
  {
    index: 5,
    stepper_type: 'property_deal',
    title: 'Deal Timeline',
    title_ar: 'الجدول الزمني للصفقة',
    sections_attributes: [
      {
        index: 0,
        title: 'Select date',
        title_ar: nil,
        description: nil,
        description_ar: nil,
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'start date',
            statement_ar: 'تاريخ البدء',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: true,
            field_type: 'date',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'start_at',
            input_type: 'currency',
            options_attributes: []
          },
          {
            index: 1,
            statement: 'end date',
            statement_ar: 'تاريخ الانتهاء',
            label: '',
            label_ar: '',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'date',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'end_at',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      }
    ]
  },
  {
    index: 6,
    stepper_type: 'property_deal',
    title: 'terms',
    title_ar: 'شروط',
    sections_attributes: [
      {
        index: 0,
        title: 'Terms',
        title_ar: 'شروط',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: [
          {
            index: 0,
            statement: 'Agree all terms',
            statement_ar: 'أوافق على جميع الشروط',
            label: 'Description about terms',
            label_ar: 'وصف حول المصطلحات',
            description: '',
            description_ar: '',
            is_required: false,
            field_type: 'checkbox',
            permitted_types: nil,
            size_constraints: {},
            suggestions: [],
            field_mapping: 'agreed_with_kanz_terms',
            input_type: 'currency',
            options_attributes: []
          }
        ]
      }
    ]
  },
  {
    index: 7,
    stepper_type: 'property_deal',
    title: 'review',
    title_ar: 'مراجعة',
    sections_attributes: [
      {
        index: 0,
        title: 'Review',
        title_ar: 'مراجعة',
        description: '',
        description_ar: '',
        is_multiple: nil,
        add_more_label: '',
        add_more_label_ar: '',
        display_card: false,
        condition: '',
        fields_attributes: []
      }
    ]
  }
].each do |step|
  record = Stepper.find_or_initialize_by(stepper_type: step[:stepper_type], title: step[:title])
  if record.update(step)
    Rails.logger.debug { "Added Role: #{record.title}" }
  else
    Rails.logger.debug { record.errors.full_messages.to_sentence }
  end
end
