# frozen_string_literal: true

industries = [
  { name: 'Accounting', name_ar: 'المحاسبة' },
  { name: 'Advertising', name_ar: 'دعاية' },
  { name: 'Aerospace', name_ar: 'الفضاء' },
  { name: 'Agriculture', name_ar: 'زراعة' },
  { name: 'Apparel & Fashion', name_ar: 'الملابس والموضة' },
  { name: 'Architecture', name_ar: 'بنيان' },
  { name: 'Automotive', name_ar: 'السيارات' },
  { name: 'Banking', name_ar: 'الخدمات المصرفية' },
  { name: 'Biotechnology', name_ar: 'التكنولوجيا الحيوية' },
  { name: 'Chemical', name_ar: 'المواد الكيميائية' },
  { name: 'Computer Hardware', name_ar: 'أجزاء الكمبيوتر' },
  { name: 'Computer Networking', name_ar: 'شبكات الكمبيوتر' },
  { name: 'Computer Software', name_ar: 'برامج الكمبيوتر' },
  { name: 'Construction', name_ar: 'بناء' },
  { name: 'Consumer Electronics', name_ar: 'مستهلكى الكترونيات' },
  { name: 'Consumer Goods', name_ar: 'بضائع المستهلكين' },
  { name: 'Consumer Services', name_ar: 'خدمات المستهلك' },
  { name: 'Cosmetics', name_ar: 'مستحضرات التجميل' },
  { name: 'Defense & Space', name_ar: 'الدفاع والفضاء' },
  { name: 'Education Management', name_ar: 'إدارة التعليم' },
  { name: 'E-learning', name_ar: 'التعلم الإلكتروني' },
  { name: 'Electrical & Electronic Manufacturing', name_ar: 'التصنيع الكهربائي والإلكتروني' },
  { name: 'Entertainment', name_ar: 'ترفيه' },
  { name: 'Environmental Services', name_ar: 'الخدمات البيئية' },
  { name: 'Events Services', name_ar: 'خدمات المناسبات' },
  { name: 'Financial Services', name_ar: 'الخدمات المالية' },
  { name: 'Food & Beverage', name_ar: 'طعام وشراب' },
  { name: 'Food Production', name_ar: 'إنتاج الغذاء' },
  { name: 'Fundraising', name_ar: 'جمع التبرعات' },
  { name: 'Furniture', name_ar: 'أثاث' },
  { name: 'Gambling & Casinos', name_ar: 'القمار والكازينوهات' },
  { name: 'Government Administration', name_ar: 'الإدارة الحكومية' },
  { name: 'Health, Wellness & Fitness', name_ar: 'الصحة واللياقة البدنية' },
  { name: 'Hospital & Health Care', name_ar: 'المستشفى والرعاية الصحية' },
  { name: 'Hospitality', name_ar: 'ضيافة' },
  { name: 'Human Resources', name_ar: 'الموارد البشرية' },
  { name: 'Import & Export', name_ar: 'استيراد و تصدير' },
  { name: 'Individual & Family Services', name_ar: 'الخدمات الفردية والعائلية' },
  { name: 'Industrial Automation', name_ar: 'الأتمتة الصناعية' },
  { name: 'Information Services', name_ar: 'خدمات المعلومات' },
  { name: 'Information Technology & Services', name_ar: 'تكنولوجيا المعلومات والخدمات' },
  { name: 'Insurance', name_ar: 'تأمين' },
  { name: 'Internet', name_ar: 'إنترنت' },
  { name: 'Legal Services', name_ar: 'خدمات قانونية' },
  { name: 'Logistics & Supply Chain', name_ar: 'اللوجستيات وسلسلة التوريد' },
  { name: 'Luxury Goods & Jewelry', name_ar: 'السلع الفاخرة والمجوهرات' },
  { name: 'Machinery', name_ar: 'الات' },
  { name: 'Management Consulting', name_ar: 'الاستشارات الإدارية' },
  { name: 'Manufacturing', name_ar: 'تصنيع' },
  { name: 'Market Research', name_ar: 'البحث عن المتجر' },
  { name: 'Marketing & Advertising', name_ar: 'الاعلان التسويقي' },
  { name: 'Media Production', name_ar: 'الإنتاج الإعلامي' },
  { name: 'Medical Devices', name_ar: 'أجهزة طبية' },
  { name: 'Medical Practice', name_ar: 'الممارسة الطبية' },
  { name: 'Mining & Metals', name_ar: 'التعدين والمعادن' },
  { name: 'Nonprofit Organization Management', name_ar: 'إدارة المنظمات غير الربحية' },
  { name: 'Oil & Energy', name_ar: 'النفط والطاقة' },
  { name: 'Online Media', name_ar: 'وسائل الاعلام على الانترنت' },
  { name: 'Outsourcing/Offshoring', name_ar: 'الاستعانة بمصادر خارجية / الاستعانة بمصادر خارجية' },
  { name: 'Package/Freight Delivery', name_ar: 'تسليم الطرود / الشحنات' },
  { name: 'Packaging & Containers', name_ar: 'التعبئة والتغليف والحاويات' },
  { name: 'Pharmaceuticals', name_ar: 'الأدوية' },
  { name: 'Photography', name_ar: 'التصوير' },
  { name: 'Printing', name_ar: 'طباعة' },
  { name: 'Professional Training & Coaching', name_ar: 'التدريب المهني والتوجيه' },
  { name: 'Public Relations & Communications', name_ar: 'العلاقات العامة والاتصالات' },
  { name: 'Publishing', name_ar: 'نشر' },
  { name: 'Real Estate', name_ar: 'العقارات' },
  { name: 'Research', name_ar: 'بحث' },
  { name: 'Restaurants', name_ar: 'مطاعم' },
  { name: 'Retail', name_ar: 'بيع بالتجزئة' },
  { name: 'Security & Investigations', name_ar: 'الأمن والتحقيقات' },
  { name: 'Semiconductors', name_ar: 'أشباه الموصلات' },
  { name: 'Shipbuilding', name_ar: 'بناء السفن' },
  { name: 'Sporting Goods', name_ar: 'بضائع رياضيه' },
  { name: 'Sports', name_ar: 'رياضات' },
  { name: 'Staffing & Recruiting', name_ar: 'الموظفون والتوظيف' },
  { name: 'Telecommunications', name_ar: 'الإتصالات' },
  { name: 'Textiles', name_ar: 'المنسوجات' },
  { name: 'Translation & Localization', name_ar: 'الترجمة والتعريب' },
  { name: 'Transportation/Trucking/Railroad', name_ar: 'النقل / النقل بالشاحنات / السكك الحديدية' },
  { name: 'Travel & Tourism', name_ar: 'رحلة سياحية' },
  { name: 'Utilities', name_ar: 'خدمات' },
  { name: 'Venture Capital & Private Equity', name_ar: 'رأس المال الاستثماري وحقوق الملكية الخاصة' },
  { name: 'Veterinary', name_ar: 'طبيب بيطري - بيطري' },
  { name: 'Warehousing', name_ar: 'التخزين' },
  { name: 'Wholesale', name_ar: 'بالجملة' },
  { name: 'Wine & Spirits', name_ar: 'النبيذ والمشروبات الروحية' },
  { name: 'Wireless', name_ar: 'لاسلكي' },
  { name: 'Writing & Editing', name_ar: 'الكتابة والتحرير' },
  { name: 'Other', name_ar: 'آخر' },
  { name: 'Renewable & Environment', name_ar: 'الطاقة المتجددة والبيئة' },
  { name: 'Information & Communication Technology', name_ar: 'تكنولوجيا المعلومات والاتصالات' },
  { name: 'Data & Analytics', name_ar: 'تحليلات البيانات' },
  { name: 'Digital Marketing', name_ar: 'التسويق الرقمي' },
  { name: 'Design', name_ar: 'تصميم' },
  { name: 'E-commerce', name_ar: 'التجارة الإلكترونية' },
  { name: 'Financial Technology', name_ar: 'التكنولوجيا المالية' },
  { name: 'Health Technology', name_ar: 'تكنولوجيا الصحة' },
  { name: 'Legal', name_ar: 'قانوني' }
]
industries.each do |industry|
  record = Industry.find_or_initialize_by(name: industry[:name])

  if record.update(industry)
    Rails.logger.debug { "Added industry: #{industry[:name]}" }
  else
    Rails.logger.debug { "Failed to save industry: #{record.errors.full_messages.to_sentence}" }
  end
end
